namespace BuzzMe.Domain.Invitations;

/// <summary>
/// The expiring, single-use, externally-shareable credential an Invitation is addressed by
/// (DOMAIN_MODEL.md's Invitation invariants; API_CONTRACT.md §5's `{token}` path parameter).
/// Deliberately not a GUIDv7 like every other aggregate ID in this codebase — GUIDv7 is
/// time-sortable by design (DEVELOPMENT_GUIDE.md §9), which is exactly the wrong property
/// for a bearer credential: sortability leaks creation order and reduces the effective
/// search space for guessing. Generated by <see cref="IInvitationTokenGenerator"/> instead.
/// </summary>
public readonly record struct InvitationToken(string Value)
{
    public override string ToString() => Value;
}
